using System;
using ConsoleApp;

[assembly: NServiceBusEndpointName(Program.EndpointName)]

namespace ConsoleApp
{
    class Program
    {
        public const string EndpointName = "sales";

        static void Main(string[] args)
        {
            HelloWorldGenerated.HelloWorld.SayHello();

            Console.WriteLine($"EndpointConfiguration would use: {Program.EndpointName}");
            Console.WriteLine($"Autogenerated: {FunctionEndpointTrigger.Name}");
        }
    }
}
