using System;
using ConsoleApp;

[assembly: NServiceBusEndpointName(Program.EndpointName)]

namespace ConsoleApp
{
    class Program
    {
        public const string EndpointName = "sales";

        static void Main(string[] args)
        {
            Console.WriteLine($"EndpointConfiguration would use: {Program.EndpointName}");

            //class Startup : FunctionsStartup
            //{
            //  public override void Configure(IFunctionsHostBuilder builder)
            //  {
            //    builder.UseNServiceBus(() => new ServiceBusTriggeredEndpointConfiguration(Program.EndpointName)); // trigger function will use this name as well
            //  }
            //}

            Console.WriteLine($"Autogenerated: {nameof(FunctionEndpointTrigger)}");
        }
    }
}